@startuml

interface IDBArrayKey
interface IDBKeyRange

Key <-- string
Key <-- number
Key <-- Date
Key <-- ArrayBufferView
Key <-- ArrayBuffer
Key <-- IDBArrayKey
Key <-- IDBKeyRange

interface CrudApi<T> {
  create(obj: T): Promise<T|undefined>
  update(obj: T): Promise<T|undefined>
  delete(obj: T): Promise<boolean>
  get(id: Key): Promise<T|undefined>
  gets(): Promise<T[]>
}

interface StoreIndex {
  string name
	string? keyPath
	boolean? unique
}

interface StoreSchema {
  string dbName
	number dbVersion
	string store
	string? keyPath
	StoreIndex[] indices
  (IDBDatabase): Promise<boolean>? onUpgradeNeeded
}

interface CheckApiOnline {
  isOnline(): Promise<boolean>
}

class Database<T> {
  string key
  CrudApi<T>? api
  StoreSchema schema
}

class RestfulDb {
  Record<string, Database> databases

  addDatabase(db: Database<T>): void
  gets<T>(schemaKey: string): Promise<T[]>
  get<T>(id: Key, schemaKey: string): Promise<T|undefined>
  create<T>(obj: T, schemaKey: string): Promise<T|undefined>
  update<T>(obj: T, schemaKey: string): Promise<T|undefined>
  delete<T>(obj: T, schemaKey: string): Promise<boolean>

  goingOnline(): void
  sync(): void
  syncDatabase<T>(database: Database<T>): void
}

@enduml
